name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        NASA: ${{ secrets.NASA_API_KEY }}
        RANDOM_DATA: ${{ secrets.RANDOM_DATA_API_KEY }}
      run: |
        echo $NASA >> secrets.txt
        echo $RANDOM_DATA >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
